# Generated by Django 3.1.3 on 2020-12-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region_id',
        ),
    ]
