# Generated by Django 3.1.3 on 2020-12-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_remove_region_region_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='regions',
            field=models.ManyToManyField(to='maps.Region'),
        ),
    ]
